// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvwotqerxmohasszzybs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2d290cWVyeG1vaGFzc3p6eWJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5Mzc2MjUsImV4cCI6MjA3NzUxMzYyNX0.2aaNglmJ2s-z8nnv0TPWBcawx4xSioldmKzCvjUlqaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});